config/routes.rb
Rails.application.routes.draw do
  
  get 'book/new'
  get 'book/edit'
  get 'book/destroy'
  get 'admin/new'
  get 'admin/create'
  get 'admin/destroy'
   get 'home/index'
   root 'home#index'
  # get 'admin/index'
  # get 'admin/destory'
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  resources :users
  resources :sessions, only:[:new,:create,:destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'reserve/:id', to: 'home#reserve'
  get 'cancel/:id', to: 'home#cancel'

  resources :admin, only:[:new ,:create]
  get 'admin_logout', to: 'admin#destroy', as: 'admin_logout'
  get 'admin', to: 'admin#new', as: 'admin'
  get 'admin_login', to: 'admin#index', as: 'admin_login'

  get '/book/add', to: 'book#new'
  get '/book/create', to: 'book#create'
  get '/book/edit/:id', to: 'book#edit'
  delete '/book/:id', to: 'book#destroy'

  get '/book/r_user', to: 'book#r_user'
  get '/r_list', to: 'home#r_list'
  get '/search', to: 'home#search' 

  post 'update/:id', to: 'book#update'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true  
  
end

app/models/book.rb
class Book < ApplicationRecord
	def self.search(search)
		if search
			where("category LIKE ?","%" + params[:search] + "%")
		else
			all
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true,uniqueness:true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  skip_before_action :require_login,only:[:new,:create]
  def new
  end

  def create
  	admin = Admin.find_by_name(params[:name])
  	if admin && admin.authenticate(params[:password])
  		session[:admin_id] = admin.id
  		redirect_to admin_login_url, notice: "Welcome to admin!"
  	else
  		flash.now[:alert] = "Name or password is invalid!"
  		render "new"
  	end
  end

  def index
  	@book = Book.all
  end

  def destroy
  	session[:admin_id] = nil
  	redirect_to root_url,notice: "Admin Logged Out!"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user
	helper_method :current_admin
	
	before_action :require_login
 
	private
	 
	  def require_login
	    unless Admin.find_by(id: session[:admin_id])
	      
	      redirect_to root_url, notice: "You must be logged in to access this section"
	    end
	end

	private
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def current_admin
		@current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id]
	end
end

app/controllers/book_controller.rb
class BookController < ApplicationController
  skip_before_action :require_login, only: [:new]
  def new
  	
  end
  def create
    	book = Book.new(book_params)
  	if book.save
  		redirect_to admin_login_url 
  	else
  		flash[:errors] = book.errors.full_messages
  		redirect_to "/book/add"	
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def destroy
  	book = Book.find(params[:id])
	book.destroy
	redirect_to admin_login_url
  end
  def r_user
  	@user = Book.where(r_status:"yes")
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      redirect_to admin_login_url
    else
    flash.now[:alert] = "Update Error!"
    redirect_to admin_login_url 
    end 
  end

  private
  	def book_params
  		params.require(:book).permit(:title,:author,:p_year,:price,:category,:r_status,:img)
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login, only:[:index,:reserve,:cancel,:r_list,:search]
  def index
  	@books = Book.all
  end

  def reserve
  	book = Book.find(params[:id])
  	if book.update(r_status:"yes",r_user: current_user.name)
		redirect_to root_url
	else
		flash.now[:alert] = "Error!"
		redirect_to root_url	
	end
  end
  def cancel
 	book = Book.find (params[:id])
   	if book.update(r_status:"no",r_user: " ")
   		redirect_to root_url
   	else
  		flash.now[:alert] = "Error!"
  		redirect_to root_url	
   	end
  end

  def r_list
    @list = Book.where(r_user:current_user.name)
  end

  def search
    @books = Book.where("category LIKE ?","%" + params[:search] + "%")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new,:create,:destroy]
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to root_url, notice: "Logged In!"
  	else
  		flash.now[:alert] = "Email or password is invalid!"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_url,notice: "Logged Out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new,:create,:update,:index]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :address)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/create.html.erb
<h1>Admin#create</h1>
<p>Find me in app/views/admin/create.html.erb</p>

app/views/admin/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
	<a class="navbar-brand" href="#"><h3><b>Zwenex Bookshop</b></h3></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	    <% if current_admin %>		
		  <li class="nav-item">	      	
	      	<b><a href="#" class="nav-link" style="text-transform: uppercase;">Welcome '<%= current_admin.name %>'</a></b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Log Out',admin_logout_path , class:"nav-link" %> </b>
	      </li>
	    <% end %>
	    </ul>
	  </div>
	</div>
</nav>
<div class="container">
	<p id='notice'><%= notice %></p>

	<br>
	<h3><b>BOOK LISTS</b></h3>
	<br>
	<p align="right"><a href="/book/r_user" class="btn btn-ouline-info">Reserved user list</a></p>
	<div style="height: 5px;"></div>
	<table class="table">
		<tr>
			<th>Title</th>
			<th>Author</th>
			<th>Price</th>
			<th>Published Year</th>
			<th>Category</th>
			<th>Other</th>
		</tr>
		<% @book.each do |b| %>
		<tr>
			<td><%= b.title %></td>
			<td><%= b.author %></td>
			<td><%= b.price %></td>
			<td><%= b.p_year %></td>
			<td><%= b.category %></td>
			<td><a href="/book/edit/<%= b.id %>" class="btn btn-info">Edit</a>
				<a href="/book/<%= b.id %>"  data-method=delete data-confirm="Are you sure?" class="btn btn-danger">Del</a></td>
		</tr>
		<% end %>
	</table>
	<br>
	<a href="/book/add" class="btn btn-primary">Add New Book</a>
</div>

app/views/admin/new.html.erb
<div class="container">
	<p id='alert'><%= alert %></p>
	<h3><b>ADMIN LOGIN</b></h3>
	<br>
	<%= form_tag admin_path do |form| %>
	<div class="field">
		<%= label_tag :name  %>
		<%= text_field_tag :name%>
	</div>
	<div class="field">
		<%= label_tag :password %>
		<%= password_field_tag :password %>
	</div>
	<br>
	<div class="actions">
		<%= submit_tag 'Login',class:"btn btn-primary btn-xs" %>
	</div>
	<% end %>

	<br>
	<%= link_to 'Back', home_index_path %>
</div>

app/views/book/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
	<a class="navbar-brand" href="#"><h3><b>Zwenex Bookshop</b></h3></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	    <% if current_admin %>		
		  <li class="nav-item">	      	
	      	<b><a href="#" class="nav-link" style="text-transform: uppercase;">Welcome '<%= current_admin.name %>'</a></b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Log Out',admin_logout_path , class:"nav-link" %> </b>
	      </li>
	    <% end %>
	    </ul>
	  </div>
	</div>
</nav>
<br><br>
<div class="container">
	<h3>Edti Book</h3>
	<br>
		<form action="/update/<%= @book.id %>" method="post">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	  <div class="form-group row">
	    <label for="staticEmail" class="col-sm-2 col-form-label">Title :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="staticEmail" name="book[title]" value="<%= @book.title %>">
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="author" class="col-sm-2 col-form-label">Author :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="author" name="book[author]" value="<%= @book.author %>">
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="price" class="col-sm-2 col-form-label">Price :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="price" name="book[price]" value="<%= @book.price %>">
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="p_year" class="col-sm-2 col-form-label">Published Year :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="p_year" name="book[p_year]" value="<%= @book.p_year %>">
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="category" class="col-sm-2 col-form-label">Category :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="category" name="book[category]" value="<%= @book.category %>">
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="img" class="col-sm-2 col-form-label">Image :</label>
	    <div class="col-sm-10">
	      <input type="file" id="img" name="book[img]" value="<%= @book.img %>">
	    </div>
	  </div>
	  <br>
  	  <button type="submit" class="btn btn-primary" style="width: 100%;padding: 10px 0;">Update Book</button>
	  
	</form>
	<br>
	<%= link_to 'Back', admin_login_path %>
</div>

app/views/book/new.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
	<a class="navbar-brand" href="#"><h3><b>Zwenex Bookshop</b></h3></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	    <% if current_admin %>		
		  <li class="nav-item">	      	
	      	<b><a href="#" class="nav-link" style="text-transform: uppercase;">Welcome '<%= current_admin.name %>'</a></b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Log Out',admin_logout_path , class:"nav-link" %> </b>
	      </li>
	    <% end %>
	    </ul>
	  </div>
	</div>
</nav>
<br><br>
<div class="container">
	<h3><b>ADD NEW BOOK</b></h3>
	<br>
	<form action="/book/create" method="get">
		<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	  <div class="form-group row">
	    <label for="staticEmail" class="col-sm-2 col-form-label">Title :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="staticEmail" name="book[title]" required>
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="author" class="col-sm-2 col-form-label">Author :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="author" name="book[author]" required>
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="price" class="col-sm-2 col-form-label">Price :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="price" name="book[price]" required>
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="p_year" class="col-sm-2 col-form-label">Published Year :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="p_year" name="book[p_year]" required>
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="category" class="col-sm-2 col-form-label">Category :</label>
	    <div class="col-sm-10">
	      <input type="text" class="form-control" id="category" name="book[category]" required>
	    </div>
	  </div>
	  <div class="form-group row">
	    <label for="img" class="col-sm-2 col-form-label">Image :</label>
	    <div class="col-sm-10">
	      <input type="file" id="img" name="book[img]" required>
	    </div>
	  </div>
	  <input type="hidden" name="book[r_status]" value="no" >
	  <br>
  	  <button type="submit" class="btn btn-primary" style="width: 100%;padding: 10px 0;">Add Book</button>
	  
	</form>
	<br>
	<%= link_to 'Back', admin_login_url %>
</div>

app/views/book/r_user.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
	<a class="navbar-brand" href="#"><h3><b>Zwenex Bookshop</b></h3></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	    <% if current_admin %>		
		  <li class="nav-item">	      	
	      	<b><a href="#" class="nav-link" style="text-transform: uppercase;">Welcome '<%= current_admin.name %>'</a></b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Log Out',admin_logout_path , class:"nav-link" %> </b>
	      </li>
	    <% end %>
	    </ul>
	  </div>
	</div>
</nav>
<br>
<br>
<div class="container">
	<h3><b>Reserved User Lists</b></h3>
	<table class="table">
		<tr>
			<th>Username</th>
			<th>Book Title</th>
			<th>Others</th>
		</tr>
		<% @user.each do |u|%>
		<tr>
			<td><%= u.r_user %></td>
			<td><%= u.title %></td>
			<td><a href="/r_cancel/<%= u.id %>" class="btn btn-danger">Cancel</a></td>
		</tr>
		<% end %>
	</table>
	<br>
	<%= link_to "Back",admin_login_path%>
</div>

app/views/home/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
	<a class="navbar-brand" href="#"><h3><b>Zwenex Bookshop</b></h3></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	    <% if current_user %>		
		  <li class="nav-item">	      	
	      	<b><a href="#" class="nav-link" style="text-transform: uppercase;">Welcome '<%= current_user.name %>'</a></b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Log Out',logout_path , class:"nav-link" %> </b>
	      </li>
		<% else %>
	      <li class="nav-item">	      	
	      	<b><%= link_to 'Log In',login_path, class:"nav-link" %> </b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Sign up',signup_path, class:"nav-link" %> </b>
	      </li>
	    <% end %>
	    </ul>
	  </div>
	</div>
</nav>
<br><br>
<div class="container">
<p id="notice"><%= notice %></p>

<h4 style="font-weight: bold;text-transform: uppercase;">Book list</h4>

<form method="get" action="/search">
      <div class="row">
      	<div class="col-md-11">
      		<input class="form-control mr-sm-2" type="search" placeholder="Search Book Category" aria-label="Search" name="search"> 
      	</div>
      	<div class="col-md-1">
      		 <button class="btn btn-outline-danger" type="submit">Search</button>
      	</div>
      </div>
</form>
<br>
<% if current_user%>
	<a href="/r_list" class="btn btn-outline-primary">Reserved list</a></p>
<% end%>
<p>
<br>
<div class="row">

	<% @books.each do |b| %>


	<div class="col-md-3">
		<a href="#">
			<div class="card">
			  <img class="card-img-top" src="/assets/<%= b.img %>" alt="Card image cap">
			  <div class="card-body">
			    <h6 class="card-title" style="color: #000;">Title : <b><%= b.title %></b></h6>	    
			    <p class="card-title" style="color: #000;">Category : <b><%= b.category %></b></p> 
			    <p class="card-title" style="color: #000;">Price : <b>$ <%= b.price %></b></p>	    
			  </div>
			</div>
		</a>
		<div style="height: 10px;"></div>

		<% if current_user %>
			<% if b.r_status == "no" %>
				<a href="/reserve/<%= b.id %>"><button class="btn btn-xs btn-info" style="width: 100%;">Reserve</button></a>
			<% elsif b.r_status == "yes" && b.r_user == current_user.name %>
				<a href="/cancel/<%= b.id %>"><button class="btn btn-xs btn-danger" style="width: 100%;">Cancel</button></a>			<% else %>
			<button class="btn btn-xs btn-default" disabled  style="width: 100%;"> Reserved</button> 
			<% end %>
		<% end %>

			<% if current_user%>
			<button class="btn btn-xs btn-default" style="width: 100%;display:none;">Please login for reserve!</button> 
			<% else %>
			<button class="btn btn-xs btn-default" disabled  style="width: 100%;">Please login for reserve!</button> 
			
			<% end%>
			<div style="height: 25px;"></div>
	</div>

	<% end %>
</div>
</div>

app/views/home/r_list.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
	<a class="navbar-brand" href="#"><h3><b>Zwenex Bookshop</b></h3></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	    <% if current_user %>		
		  <li class="nav-item">	      	
	      	<b><a href="#" class="nav-link" style="text-transform: uppercase;">Welcome '<%= current_user.name %>'</a></b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Log Out',logout_path , class:"nav-link" %> </b>
	      </li>
		<% else %>
	      <li class="nav-item">	      	
	      	<b><%= link_to 'Log In',login_path, class:"nav-link" %> </b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Sign up',signup_path, class:"nav-link" %> </b>
	      </li>
	    <% end %>
	    </ul>
	  </div>
	</div>
</nav>
<br><br>
<div class="container">
	<h3>MY RESERVE LIST</h3>
	<br>
	<table class="table">
		<tr>
			<th>Title</th>
			<th>Author</th>
			<th>Price</th>
			<th>Published Year</th>
			<th>Category</th>
			<th>OTHER</th>
		</tr>
		<% @list.each do |l| %>
		<tr>
			<td><%= l.title %></td>
			<td><%= l.author %></td>
			<td><%= l.price %></td>
			<td><%= l.p_year %></td>
			<td><%= l.category %></td>
			<td><a href="/cancel/<%= l.id %>" class="btn btn-danger">Cancel</a></td>
		</tr>
		<% end %>
	</table>
	<br>
	<%= link_to "Back", root_path %>
</div>

app/views/home/search.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
	<a class="navbar-brand" href="#"><h3><b>Zwenex Bookshop</b></h3></a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav ml-auto">
	    <% if current_user %>		
		  <li class="nav-item">	      	
	      	<b><a href="#" class="nav-link" style="text-transform: uppercase;">Welcome '<%= current_user.name %>'</a></b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Log Out',logout_path , class:"nav-link" %> </b>
	      </li>
		<% else %>
	      <li class="nav-item">	      	
	      	<b><%= link_to 'Log In',login_path, class:"nav-link" %> </b>
	      </li>
	      <li class="nav-item ">
	        <b><%= link_to 'Sign up',signup_path, class:"nav-link" %> </b>
	      </li>
	    <% end %>
	    </ul>
	  </div>
	</div>
</nav>
<br><br>
<div class="container">
<p id="notice"><%= notice %></p>

<h4 style="font-weight: bold;text-transform: uppercase;">Book list</h4>

<form method="get" action="/search">
      <div class="row">
      	<div class="col-md-11">
      		<input class="form-control mr-sm-2" type="search" placeholder="Search Book Category" aria-label="Search" name="search"> 
      	</div>
      	<div class="col-md-1">
      		 <button class="btn btn-outline-danger" type="submit">Search</button>
      	</div>
      </div>
</form>
<br>
<% if current_user%>
	<a href="/r_list" class="btn btn-outline-primary">Reserved list</a></p>
<% end%>
<p>
<br>
<div class="row">

	<% @books.each do |b| %>


	<div class="col-md-3">
		<a href="#">
			<div class="card">
			  <img class="card-img-top" src="/assets/<%= b.img %>" alt="Card image cap">
			  <div class="card-body">
			    <h6 class="card-title" style="color: #000;">Title : <b><%= b.title %></b></h6>	    
			    <p class="card-title" style="color: #000;">Category : <b><%= b.category %></b></p> 
			    <p class="card-title" style="color: #000;">Price : <b>$ <%= b.price %></b></p>	    
			  </div>
			</div>
		</a>
		<div style="height: 10px;"></div>

		<% if current_user %>
			<% if b.r_status == "no" %>
				<a href="/reserve/<%= b.id %>"><button class="btn btn-xs btn-info" style="width: 100%;">Reserve</button></a>
			<% elsif b.r_status == "yes" && b.r_user == current_user.name %>
				<a href="/cancel/<%= b.id %>"><button class="btn btn-xs btn-danger" style="width: 100%;">Cancel</button></a>			<% else %>
			<button class="btn btn-xs btn-default" disabled  style="width: 100%;"> Reserved</button> 
			<% end %>
		<% end %>

			<% if current_user%>
			<button class="btn btn-xs btn-default" style="width: 100%;display:none;">Please login for reserve!</button> 
			<% else %>
			<button class="btn btn-xs btn-default" disabled  style="width: 100%;">Please login for reserve!</button> 
			
			<% end%>
			<div style="height: 25px;"></div>
	</div>

	<% end %>
</div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th colspan="3">Others</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

</div>

app/views/users/new.html.erb
<div class="container">
	<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', home_index_path %>

</div>